name: PR-label -> clean-up dev env

on:
  pull_request:
    types: [closed]

jobs:
  preview:
    name: Clean up dev environment
    runs-on: ubuntu-latest
    continue-on-error: true # Ignore errors
    steps:
      - name: Check PR env labels
        uses: voiceflow/pr-label-match@master
        if: github.event.action == 'closed'
        with:
          regex: env-
        id: envNameLabel

      - name: Remove environment label
        uses: buildsville/add-remove-label@v1
        if: github.event.action == 'closed'
        with:
          token: ${{secrets.GH_SA_TOKEN}}
          label: ${{ steps.envNameLabel.outputs.label}}
          type: remove

      - name: Install vfcli
        if: github.event.action == 'closed' && steps.envNameLabel.outputs.label != ''
        env:
          GITHUB_TOKEN: ${{ secrets.GH_SA_TOKEN }}
        run: |
          API_URL="https://$GITHUB_TOKEN:@api.github.com/repos/voiceflow/vfcli"
          ASSET_ID=$(curl $API_URL/releases/latest | jq -r '.assets[3].id')
          curl -J -L -H "Accept: application/octet-stream" "$API_URL/releases/assets/$ASSET_ID" --output vfcli.tar.gz
          tar -xf vfcli.tar.gz

      - name: Delete the dev env if PR closed not creating and the label exists
        if: github.event.action == 'closed' && steps.envNameLabel.outputs.label != ''
        id: deleteEnv
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"
        run: |
          echo "Initializating vfcli..."
          ./vfcli init --interactive false

          # Remove environmnet
          ./vfcli env delete -n ${{ steps.envNameLabel.outputs.label}} --interactive false
          echo -e "::set-output name=deleted::true"

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@master
        if: steps.deleteEnv.outputs.deleted == 'true'
        with:
          message: "Dev environment ${{ steps.envNameLabel.outputs.label}} destroyed!"
          GITHUB_TOKEN: ${{ secrets.GH_SA_TOKEN }}
