name: PR-label -> preview dev env

on:
  pull_request:
    types: [reopened, labeled]

jobs:
  preview:
    name: Preview commit on env
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Check PR env labels
        uses: voiceflow/pr-label-match@master
        with:
          regex: "env-"
        id: envNameLabel
      - name: Check for new env request
        uses: Dreamcodeio/pr-has-label-action@master
        id: newEnvLabel
        with:
          label: new-env
      - name: Install vfcli
        env:
          GITHUB_TOKEN: ${{ secrets.GH_SA_TOKEN }}
        run: |
          API_URL="https://$GITHUB_TOKEN:@api.github.com/repos/voiceflow/vfcli"
          ASSET_ID=$(curl $API_URL/releases/latest | jq -r '.assets[3].id')
          curl -J -L -H "Accept: application/octet-stream" "$API_URL/releases/assets/$ASSET_ID" --output vfcli.tar.gz
          tar -xf vfcli.tar.gz

      - name: Create new environment if applicable
        if: steps.newEnvLabel.outputs.hasLabel == 'true' && steps.envNameLabel.outputs.label == ''
        id: createNewEnv
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"
        run: |
          sleep $[ ( $RANDOM % 10 ) ]s # Add dither to desync multiple tag request firings

          echo "Initializating vfcli..."
          ./vfcli init --interactive false --no-telepresence

          echo "Creating new environment..."
          ./vfcli env create xavi --interactive false --no-telepresence
          # From the vfcli config file, gets the value from the name YAML property and the replace " to empty
          ENV_NAME=$(cat /home/runner/.vfcli.yaml | grep test- | awk '/name:/ {print $2}' | sed 's/"//g' )

          NEW_LABEL="env-${ENV_NAME}"

          # Get all components and retrieve the line that has the json output
          COMPONENT_URL=$(./vfcli component list  --interactive false --verbose --output json  --no-telepresence -n ${ENV_NAME} | grep { | jq -cr '.[] | select(.id | contains("creator-app")).endpoint')
          echo ${COMPONENT_URL}

          echo -e "::set-output name=newEnvName::${ENV_NAME}"
          echo -e "::set-output name=newLabel::${NEW_LABEL}"
          echo -e "::set-output name=endpoint::${COMPONENT_URL}"

      - name: Tag PR with new environment name
        uses: buildsville/add-remove-label@v1
        if: steps.newEnvLabel.outputs.hasLabel == 'true' && steps.envNameLabel.outputs.label == ''
        with:
          token: ${{secrets.GH_SA_TOKEN}}
          label: ${{ steps.createNewEnv.outputs.newLabel }}
          type: add

      - name: Remove new-env label (if exist)
        uses: buildsville/add-remove-label@v1
        if: steps.newEnvLabel.outputs.hasLabel == 'true' && steps.envNameLabel.outputs.label == ''
        with:
          token: ${{secrets.GH_SA_TOKEN}}
          label: new-env
          type: remove

      - name: Preview tracking
        if: steps.newEnvLabel.outputs.hasLabel == 'true' && steps.envNameLabel.outputs.label == ''
        id: preview
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"
        run: |
          echo "Initializating vfcli..."
          ./vfcli init --interactive false

          echo "Creating track..."
          COMPONENT=$(echo "${GITHUB_REPOSITORY}" | sed 's:.*/::')
          BRANCH="$(echo ${GITHUB_HEAD_REF#refs/heads/})"
          ./vfcli track create -n  ${{ steps.createNewEnv.outputs.newEnvName }} -c $COMPONENT -b $BRANCH --interactive false --no-telepresence

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@master
        if: steps.newEnvLabel.outputs.hasLabel == 'true' && steps.envNameLabel.outputs.label == ''
        with:
          message: "Dev environment ${{ steps.createNewEnv.outputs.newEnvName }} created!"
          GITHUB_TOKEN: ${{ secrets.GH_SA_TOKEN }}

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@master
        if: steps.newEnvLabel.outputs.hasLabel == 'true' && steps.envNameLabel.outputs.label == ''
        with:
          message: "https://${{ steps.createNewEnv.outputs.endpoint }}"
          GITHUB_TOKEN: ${{ secrets.GH_SA_TOKEN }}
