name: "Update Pull Request Title"
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  update_pr_title:
    runs-on: ubuntu-latest
    steps:
    - name: Get branch name
      if: ${{ github.actor != 'github-actions' }}
      id: branch-name
      uses: tj-actions/branch-names@v6
    - uses: tzkhan/pr-update-action@v2
      if: ${{ github.actor != 'github-actions' && !contains(github.event.pull_request.title, '[breakglass]') && contains(steps.branch-name.outputs.head_ref_branch, 'break-glass') }}
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        head-branch-regex: '.+'
        title-template: ' [breakglass]'
        title-update-action: suffix
    - uses: tzkhan/pr-update-action@v2
      if: ${{ github.actor != 'github-actions' && !contains(github.event.pull_request.title, '[bugfix]') && (contains(steps.branch-name.outputs.head_ref_branch, 'bug-fix') || contains(steps.branch-name.outputs.head_ref_branch, 'bugfix') )}}
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        head-branch-regex: '.+'
        title-template: ' [bugfix]'
        title-update-action: suffix

